import type { Metadata } from "next";
import './globalsStyles/normalize.css'
import "./globalsStyles/globals.css";
import Layout from "@/app/components/layouts/Layout";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
